Fix for #146
System.Configuration.ConfigurationErrorsException: Failed to save settings: The configuration file has been changed by another program. (\\xxx.xxx.xxx.xxx\CN_HOMES\xxx\AppData\Roaming\XCP-ng\XenCenterMain.exe_Url_zgy2ft4zhzkcejgr02qwwlngl4rqizyf\7.6.3.20\user.config