Integrade changes from master-7.4 into master (https://github.com/xcp-ng/xenadmin/issues/68)
proper fix: use Path to TestDirectory

https://github.com/nunit/docs/wiki/Breaking-Changes

CurrentDirectory:
No longer set to the directory containing the test assembly. Use TestContext.CurrentContext.TestDirectory to locate that directory.
fix Test CertificateDialogTests

Path to the Cert was build as:
 xenadmin\TestResources\TestDevCertificate.cer

but should be:
 xenadmin\XenAdminTests\TestResources\TestDevCertificate.cer
fix Test TestFailingReaderGeneration

Ionic.BZip2 is throwing an IOException:
System.IO.IOException: 'Not a valid BZip2 stream. byte 0, expected '66', got '-1''
use update.xml in master brach on github (as a first solution)

https://github.com/xcp-ng/xenadmin/issues/29

Do not check for ContainerCapability on XCP-ng, just belive in it :-)

If server is in not licenced, don't show alert icon

Changed SetUp to OneTimeSetup in SetUpFixture

https://github.com/xcp-ng/xenadmin/issues/24

abort, if BUILD_NUMBER environment variable is not set

build automation

Ignore ".vs" folder
splash buildable with Visual Studio Community 2018

https://github.com/xcp-ng/xenadmin/issues/24 Get Tests running

https://github.com/xcp-ng/xenadmin/issues/24 Get Tests running

real world: edition "platinum" has changed to "desktop-plus"

https://github.com/xcp-ng/xenadmin/issues/24 Get Tests running

set culture to "en-EN" to ensure correct parsing

https://github.com/xcp-ng/xenadmin/issues/24 Get Tests running

correct adaption to nunit 3

adapt to nunit 3

adapt path

real world: edition "platinum" has changed to "desktop-plus"

Use Nunit and Moq from NuGet; Adapt tests to Nunit 3

https://github.com/xcp-ng/xenadmin/issues/24 Get Tests running

Fill AssemblyFileVersion

Idea from https://github.com/xcp-ng/xenadmin/issues/17 Show Version in Title

Tidy up Branding/Trademarks/License

https://github.com/xcp-ng/xenadmin/issues/18

Comment unreachable code to be buildable (https://github.com/xcp-ng/xenadmin/issues/14#issuecomment-380041068)

XCP-ng Console should connect to any flavor of XenServer

(cherry picked from commit 7e2342534d75193685139226fcaf89bb365fc706)